name: MCP

on:
  push:
    branches: ["main", "testing" , "setup-pipeline"]
  pull_request:
    branches: ["main", "testing"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Show Node and npm versions
      run: |
        node -v
        npm -v
    - run: npm ci
    
    - name: Prettier format check
      run: npm run format:check
    
    - name: Clean dist (Linux)
      run: rm -rf dist || true
    - run: npm run build --if-present

    - name: Test 
      run: npm test 



